version: "3.1"

services:
  redis:
    image: redis:4
    ports:
      - "6379:6379"
  mongodb:
    image: mongo:3.7
    ports:
      - "27017:27017"
  memcached:
    image: memcached:1.5.4
    ports:
      - "11211:11211"